name: Django CI

on:
  push:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.11

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Install Git and Lint Dependencies
        run: |
          apt update
          pip install --upgrade pip
          pip install pre-commit autoflake
          
      - name: Run Linting
        run: |
          pre-commit run -av --show-diff-on-failure

  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    env:
      GOOGLE_APPLICATION_CREDENTIALS: /home  
      TEST_RUNNER: xmlrunner.extra.djangotestrunner.XMLTestRunner
      ADD_LOGS: "false"
      SQL_ENGINE: "django.db.backends.postgresql"
      SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
      SQL_USER: ${{ secrets.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_HOST: ${{ secrets.SQL_HOST }}

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: ${{ secrets.SQL_DATABASE }}
          POSTGRES_USER: ${{ secrets.SQL_USER }}
          POSTGRES_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python environment and Install Dependencies
        run: |
            python -m venv venv
            bash -c "source venv/bin/activate && pip install --upgrade pip && cd backend && pip install -r requirements.txt"

      - name: Run Tests
        run: |
          source venv/bin/activate
          pip install 'psycopg2>=2.8.4,<3.0'
          cd backend/src && python manage.py test --parallel
