name: Django CI

on:
  push:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.11

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Install Git and Lint Dependencies
        run: |
          apt update && apt-get install -y gettext libgettextpo-dev git
          pip install --upgrade pip
          pip install pre-commit autoflake
          
      - name: Run Linting
        run: |
          pre-commit run -av --show-diff-on-failure

  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    env:
      GOOGLE_APPLICATION_CREDENTIALS: /home  
      TEST_RUNNER: xmlrunner.extra.djangotestrunner.XMLTestRunner
      ADD_LOGS: "false"
      SQL_ENGINE: "django.db.backends.postgresql"
      SQL_DATABASE: ${{ secrets.SQL_DATABASE }}
      SQL_USER: ${{ secrets.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_HOST: ${{ secrets.SQL_HOST }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
      YANDEX_CLIENT_DOCS_BUCKET_NAME: ${{ secrets.YANDEX_CLIENT_DOCS_BUCKET_NAME }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: ${{ secrets.SQL_DATABASE }}
          POSTGRES_USER: ${{ secrets.SQL_USER }}
          POSTGRES_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        ports:
          - 5432:5432

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          python -m venv venv
          bash -c "source venv/bin/activate && pip install --upgrade pip && cd backend && pip install -r requirements.txt && cd src && python manage.py test --parallel"
